server:
  port: 9090
  host: 0.0.0.0
  id: 1
database:
  url: root:12345678@tcp(172.17.0.1:3306)/workflow_ai?parseTime=True&loc=Local
fileStoreType: tencent_cos
cos:
  bucketUrl: http://cos.ap-chengdu.myqcloud.com
  serviceUrl: https://cos.ap-chengdu.myqcloud.com
  secretId: 1234
  secretKey: 1234
vectorStoreType: redis
redis:
  host: 172.17.0.1
  port: 16379
bochaAPIKey: abcd